"""Summer camp landing page, generated with the site's shared header and footer."""
import json
from html import escape


def stage_body(root):
    data = json.loads((root / 'data/stage-ete.json').read_text(encoding='utf-8'))
    photos = data['photos']
    highlights = [3,143,83,118,188,171,193,11,44,67,72,77,105,117,130,137,153,162,174,176,186,189,192,194]
    album_photos = [photos[i-1] for i in highlights] + [p for i,p in enumerate(photos,1) if i not in highlights]
    def photo(number, alt, css=''):
        item = photos[number - 1]
        return f'<img class="{css}" src="{item["src"]}" alt="{escape(alt)}" width="{item["width"]}" height="{item["height"]}" loading="lazy" decoding="async">'
    films = ''.join(f'''<article class="stage-film"><div class="stage-film-screen"><video controls playsinline preload="none" poster="assets/stage-ete/posters-small/{v['poster'].rsplit('/',1)[-1]}" data-stage-poster="{v['poster']}" aria-label="{escape(v['title'])}"><source src="{v['src']}" type="video/mp4"></video></div><div class="stage-film-copy"><span>JOUR {i}</span><h3>{escape(v['title'])}</h3><p>{escape(v['description'])}</p></div></article>''' for i,v in enumerate(data['videos'][:5],1))
    extras = ''.join(f'''<article class="stage-film"><div class="stage-film-screen"><video controls playsinline preload="none" poster="assets/stage-ete/posters-small/{v['poster'].rsplit('/',1)[-1]}" data-stage-poster="{v['poster']}" aria-label="{escape(v['title'])}"><source src="{v['src']}" type="video/mp4"></video></div><div class="stage-film-copy"><span>DANS LES COULISSES</span><h3>{escape(v['title'])}</h3><p>{escape(v['description'])}</p></div></article>''' for v in data['videos'][5:])
    moments = ''.join(f'<figure>{photo(n,alt)}<figcaption>{label}</figcaption></figure>' for n,alt,label in [(83,'Escalade sur les rochers au bord du lac','Escalade'),(118,'Séance de tir à l’arc','Tir à l’arc'),(188,'Kayak sur le lac de Guerlédan','Kayak'),(143,'Entraînement de handball en salle','Handball'),(171,'Promenade des jeunes dans la forêt','Balade en forêt'),(193,'Un moment partagé par le groupe','La vie du groupe')])
    # All links remain in HTML; JS progressively reveals batches and enhances them with a lightbox.
    album = ''.join(f'''<a class="stage-photo" href="{p['src']}" data-stage-photo data-category="{p['category']}" aria-label="Agrandir la photo {i} du stage 2026"><img src="{p['thumb']}" alt="Stage PHB 2026 · {'Handball' if p['category']=='handball' else 'Activités de plein air' if p['category']=='aventure' else 'Vie du groupe'} · photo {i}" width="{p['width']}" height="{p['height']}" loading="lazy" decoding="async"><span aria-hidden="true">↗</span></a>''' for i,p in enumerate(album_photos,1))
    return f'''<div class="stage-page">
<section class="stage-hero" aria-labelledby="stage-title"><picture><source media="(max-width:768px)" srcset="assets/stage-ete/hero-mobile-480.webp 480w, assets/stage-ete/hero-mobile-630.webp 630w" sizes="100vw"><img class="stage-hero-image" src="assets/stage-ete/hero-1400.webp" srcset="assets/stage-ete/hero-960.webp 960w, assets/stage-ete/hero-1400.webp 1400w" sizes="100vw" alt="Le groupe de la première édition du stage PHB à Guerlédan" width="1400" height="1050" fetchpriority="high"></picture><div class="stage-hero-shade"></div><div class="container stage-hero-copy"><p class="stage-eyebrow">STAGE D’ÉTÉ PHB · U13 ET U15</p><h1 id="stage-title">STAGE D’ÉTÉ<br><em>À GUERLÉDAN</em></h1><p class="stage-lead">Une semaine de handball et d’activités de plein air à Guerlédan, pour les filles et les garçons des catégories U13 et U15.</p><div class="stage-actions"><a class="button" href="#edition-2027">LE STAGE 2027 <span>↗</span></a><a class="stage-watch" href="#films">VOIR LES VIDÉOS DE 2026 <span>▶</span></a></div></div><div class="stage-hero-tag">GUERLÉDAN <strong>LAC & BASE DE PLEIN AIR</strong></div></section>
<section class="container stage-section stage-intro" id="experience"><div class="stage-intro-picture">{photo(83,'Escalade au-dessus du lac de Guerlédan')}<span>ESCALADE AU BORD DU LAC</span></div><div class="stage-intro-copy"><p class="stage-eyebrow">LA PREMIÈRE ÉDITION</p><h2>DU HANDBALL<br><em>ET DU PLEIN AIR</em></h2><p>Du <strong>13 au 17 juillet 2026</strong>, les jeunes ont passé cinq jours à la base de plein air de Guerlédan. Au programme : entraînements de handball, escalade, tir à l’arc, kayak et beach handball.</p><p>Les journées se partageaient entre le terrain et les activités au bord du lac. C’était aussi l’occasion de passer une semaine avec les autres jeunes du groupe, en dehors des matchs et des entraînements habituels.</p><p><strong>David, Aurélien, Coraline et Erwan</strong> ont encadré cette première édition.</p><div class="stage-facts"><div><strong>5</strong><span>JOURS EN 2026</span></div><div><strong>U13 / U15</strong><span>FILLES & GARÇONS</span></div><div><strong>4</strong><span>ENCADRANTS EN 2026</span></div></div></div></section>
<section class="container stage-section" aria-labelledby="moments-title"><div class="stage-section-head"><div><p class="stage-eyebrow">AU PROGRAMME EN 2026</p><h2 id="moments-title">SUR LE TERRAIN<br><em>ET AU BORD DU LAC</em></h2></div><p>Quelques images des séances de handball et des activités proposées pendant la semaine.</p></div><div class="stage-moments">{moments}</div></section>
<section class="stage-films-section" id="films"><div class="container stage-section"><div class="stage-section-head"><div><p class="stage-eyebrow">ÉDITION 2026 · LE FILM DE LA SEMAINE</p><h2>LA SEMAINE<br><em>EN VIDÉO</em></h2></div><p>Un récapitulatif de chaque journée du stage 2026.</p></div><div class="stage-films" tabindex="0" role="region" aria-label="Les cinq récapitulatifs du stage">{films}</div><p class="stage-rail-hint">FAIS DÉFILER POUR DÉCOUVRIR LES 5 JOURNÉES →</p><h3 class="stage-extras-title">ET DANS LES COULISSES…</h3><div class="stage-films" tabindex="0" role="region" aria-label="Les vidéos des coulisses">{extras}</div></div></section>
<section class="container stage-section" id="souvenirs"><div class="stage-section-head"><div><p class="stage-eyebrow">PHOTOS DU STAGE 2026</p><h2>L’ALBUM<br><em>DU STAGE</em></h2></div><p>{len(photos)} photos de la première édition. Ouvre une image pour parcourir l’album en grand.</p></div><div class="stage-filters" aria-label="Filtrer les photos" hidden><button type="button" data-stage-filter="all" aria-pressed="true">Tout le stage</button><button type="button" data-stage-filter="handball" aria-pressed="false">Handball</button><button type="button" data-stage-filter="aventure" aria-pressed="false">L’aventure</button><button type="button" data-stage-filter="ensemble" aria-pressed="false">Ensemble</button></div><p class="stage-gallery-count" aria-live="polite"></p><div class="stage-album">{album}</div><button class="stage-more" type="button" hidden>VOIR PLUS DE PHOTOS +</button></section>
<section class="container stage-section stage-next" id="edition-2027"><div><p class="stage-eyebrow">2e ÉDITION · ÉTÉ 2027</p><h2>LE STAGE<br><em>D’ÉTÉ 2027</em></h2><p>Le PHB prépare son deuxième stage d’été à Guerlédan, pour les filles et les garçons des catégories U13 et U15.</p><p>Le stage est ouvert aux jeunes licenciés dans un club de handball. Pour en savoir plus sur la prochaine édition, contacte Erwan.</p><div class="stage-next-details"><div><span>DESTINATION</span><strong>Guerlédan</strong></div><div><span>DATES 2027</span><strong>À venir</strong></div><div><span>TARIF & INSCRIPTIONS</span><strong>À venir</strong></div></div><p class="stage-small">Le programme et les modalités de la deuxième édition seront annoncés prochainement. Les activités présentées sur cette page sont celles du stage 2026.</p><div class="stage-actions"><a class="button" href="mailto:erwanphb@gmail.com?subject=Stage%20PHB%20Guerl%C3%A9dan%202027">ME RENSEIGNER AUPRÈS D’ERWAN ↗</a><a class="stage-call" href="tel:+33622739526">06 22 73 95 26</a></div></div><div class="stage-next-image">{photo(3,'Le groupe du premier stage d’été PHB')}<span>LE GROUPE DU STAGE 2026</span></div></section>
<dialog class="stage-lightbox" aria-label="Photos du stage" data-stage-dialog><button type="button" class="stage-lightbox-close" aria-label="Fermer la photo">×</button><div class="stage-lightbox-frame"><img alt="" width="1400" height="1400"></div><div class="stage-lightbox-bar"><button type="button" data-stage-prev aria-label="Photo précédente">←</button><span aria-live="polite"></span><button type="button" data-stage-next aria-label="Photo suivante">→</button></div></dialog>
</div>'''
